# Generated by Django 5.1.1 on 2025-01-19 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='customer_code',
            field=models.CharField(error_messages={'unique': 'A customer with the provided code already exists'}, max_length=100, unique=True),
        ),
    ]
